# These are supported my directions for donations.

bitcoin: bc1qjfmye53lep5q7c8520dd7hvxx9wjcfcpyvrqx6 
litecoin: ltc1qly693gunhmfqlscfgpyrg8rz9yf395mp75vgjy
dogecoin: 0x3c0Ca7FfF0342a4170E3836264eb705Ee7A0468C
algorand: VOWDB23KJVV5FO5R3KDT5OL34FYRUQ3XTMRSNZE4XKN2GDPPUERNWPKBPE
